config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "pages#home", as: :user_root
  end
  root to: "pages#home"

  resource :profile, only: %i[edit update index]

  resources :dogs, only: %i[index show edit update] do
    resources :likes, only: %i[create]
  end

  resources :matches, only: %i[index show] do
    resources :messages, only: %i[create]
    resources :meetings, only: %i[new create destroy]
  end

  resources :meetings, only: %i[index]

  resources :places, only: %i[index new create show] do
    resources :walks, only: %i[create destroy]
    resources :reviews, only: %i[new create index]
  end
  delete "reviews/:id", to: "reviews#destroy", as: :delete_review
  get 'all_my_review', to: 'reviews#show'
  get 'home_user', to: "pages#home_user"
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_match.html.erb
<% if flash[:match] && current_user %>

  <div class="alert alert-info alert-match alert-dismissible fade show " role="alert">
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>
    <div class="confetti"></div>



    <div class="modal-content">
     <h1> Pawfect ! <br>C'est un match !</h1>
    </div>
    <div class="heart">
    <div class="dog">
      <% match = current_user.dog.matches.last %>
      <div class="gauche">
        <%= cl_image_tag match.second_dog.photos.first.key, width: 200, height: 200, crop: :fill , class: "avatar match-avatar"%>
        <h1 class= "name"><%= match.second_dog.name %></h1>
      </div>
      <div class="droite">
      <%= cl_image_tag match.dog.photos.first.key, width: 200, height: 200, crop: :fill , class: "avatar match-avatar"%>
      <h1 class="name"><%= match.dog.name %></h1>
      </div>
    </div>
      <%= link_to "Contacter mon maître", match_path(match), class: "button" %>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom">
  <%= link_to dogs_path, class: "navbar-item #{ 'active' if params[:controller] == "dogs" }" do %>
    <%= image_tag('search.svg', class:"explorer-item") %>
    <p>Explorer</p>
  <% end %>
  <%= link_to places_path, class: "navbar-item #{ 'active' if current_page?(places_path) }" do %>
    <%= image_tag('map.svg', class:"map-item") %>
    <p>Carte</p>
  <% end %>
  <%= link_to matches_path, class: "navbar-item #{ 'active' if params[:controller] == "matches" }" do %>
    <%= image_tag('heart-message.svg', class:"heart-message-item") %>
    <p>Messages</p>
  <% end %>
  <%= link_to meetings_path, class: "navbar-item #{ 'active' if current_page?(meetings_path) }" do %>
    <%= image_tag('guide-dog.svg', class:"guide-dog-item") %>
    <p>Planning</p>
  <% end %>
  <%= link_to home_user_path, class: "navbar-item" do %>
    <%= cl_image_tag current_user.dog.photos.first.key, height: 40, crop: :fill , class: "avatar"%>
    <p>Profil</p>
  <% end %>
</div>

app/views/shared/_search_bar.html.erb
<div class="search-bar">
  <%= form_with url: dogs_path, method: :get, class: "d-flex w-100" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Ville, caractère, race..."
    %>
    <button class='button-search'><%= image_tag "search-icon.svg" %></button>
  <% end %>
</div>