config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "pages#home", as: :user_root
  end
  root to: "pages#home"

  resource :profile, only: %i[edit update index]

  resources :dogs, only: %i[index show edit update] do
    resources :likes, only: %i[create]
  end

  resources :matches, only: %i[index show] do
    resources :messages, only: %i[create]
    resources :meetings, only: %i[new create destroy]
  end

  resources :meetings, only: %i[index]

  resources :places, only: %i[index new create show] do
    resources :walks, only: %i[create destroy]
    resources :reviews, only: %i[new create index]
  end
  delete "reviews/:id", to: "reviews#destroy", as: :delete_review
  get 'all_my_review', to: 'reviews#show'
  get 'home_user', to: "pages#home_user"
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
end

app/views/pages/home.html.erb
<div class="wrapper">
  <%= link_to "Voir tous les chiens", dogs_path, class: "button btn-home" %>
  <div class="scaled-wrapper">
    <div class="circle">
      <p class="element" style="font-size: 30px" id="a">🐶</p>
      <p class="element" style="font-size: 30px" id="b">💕</p>
      <p class="element" style="font-size: 30px" id="c">🌳</p>
      <p class="element" style="font-size: 30px" id="d">👥</p>
      <p class="element" style="font-size: 30px" id="e">🐕</p>
    </div>
    <p id="caption"></p>
  </div>
</div>

app/views/pages/home_user.html.erb
<div class="header-home-user">

  <div class="mask ">
    <h1> Bonjour <%= current_user.first_name %> </h1>

    <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar"%>

  </div>
  <br>
  <%= link_to "Voir tous mes avis", all_my_review_path(@reviews)%>
  <%= link_to "Se déconnecter",  destroy_user_session_path, class: "log-out", data: {turbo_method: :delete} %>
      <div class="profil-card">
        <h2>Le profil de <%= current_user.dog.name %></h2>
        <p><strong>Mon âge :</strong> <%= current_user.dog.age %></p>
        <p>Je suis un <%= current_user.dog.species %></p>
        <p><strong>Mon caractère :</strong> <%= current_user.dog.temper %></p>
        <p><strong>Mon adresse : </strong><%= current_user.dog.address %></p>
        <p><strong>Mon description : </strong><%= current_user.dog.description %></p>
        <p><strong>Mes jouets préférés: </strong><%= current_user.dog.toys %></p>
        <p class="edit-profil"><%= link_to "éditer profil", edit_dog_path(@dog)%></p>
      </div>

    <h3>Les derniers profils likés</h3>
    <% @likes.each do |like| %>
      <div class="likes-cards">
          <%=cl_image_tag like.dog.photos.first.key%>
          <span><strong><%= like.dog.name %></strong></span>
      </div>
    <% end %>
</div>