config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "pages#home", as: :user_root
  end
  root to: "pages#home"

  resource :profile, only: %i[edit update index]

  resources :dogs, only: %i[index show edit update] do
    resources :likes, only: %i[create]
  end

  resources :matches, only: %i[index show] do
    resources :messages, only: %i[create]
    resources :meetings, only: %i[new create destroy]
  end

  resources :meetings, only: %i[index]

  resources :places, only: %i[index new create show] do
    resources :walks, only: %i[create destroy]
    resources :reviews, only: %i[new create index]
  end
  delete "reviews/:id", to: "reviews#destroy", as: :delete_review
  get 'all_my_review', to: 'reviews#show'
  get 'home_user', to: "pages#home_user"
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :dog
  belongs_to :second_dog, class_name: 'Dog'
  has_many :messages, dependent: :destroy
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = current_user.dog.matches
  end

  def show
    @match = current_user.dog.matches.find(params[:id])
    @message = Message.new
    @meeting = Meeting.new
    @places = Place.all
  end
end

app/views/matches/_meeting_modal.html.erb
<div class="modal-content" data-meeting-modal-target="content">
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Planifier une balade</h5>
    <button data-meeting-modal-target="close" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <%= simple_form_for [match, meeting], url: match_meetings_path(match), method: :post, html: {
                data: {
                  turbo: false,
                  meeting_modal_target: 'form',
                  action: 'submit->meeting-modal#submit'
                }
              } do |f| %>
    <div class="modal-body">
      <%= f.input :date,
          html5: true,
          input_html: {
            class: 'date-meeting',
            data: {
              flatpickr_target: 'dateInput',
            }
          } %>
      <%= f.association :place, label: 'Lieu' %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
      <%= f.submit class: 'btn btn-primary', value: 'Planifier' %>
    </div>
  <% end %>
</div>

app/views/matches/index.html.erb
<h1 class="title-index">Tous mes matchs</h1>
<div class="cards-match">
  <% @matches.each do |match| %>
    <div class="card-match">
      <% if match.dog == current_user.dog%>
        <%= cl_image_tag match.second_dog.photos.first.key, width: 100, height: 100, crop: :fill, class: "dog-image"%>
      <% else %>
        <%= cl_image_tag match.dog.photos.first.key, width: 100, height: 100, crop: :fill, class: "dog-image"%>
      <% end %>

      <div class="match-info">
        <h2><%=match.dog == current_user.dog ? match.second_dog.name : match.dog.name %></h2>
        <p><%=l(match.created_at, format: "%a %e %b à %l:%M")%></p>
      </div>
      <%= link_to match_path(match) do %>
        <%= image_tag "chat-heart.svg", class: "heart" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/matches/show.html.erb
<div class="container match"
    data-controller="match-subscription"
    data-match-subscription-match-id-value="<%= @match.id %>"
    data-match-subscription-user-id-value="<%= current_user.id %>">

  <div class= "head">
    <% if @match.dog == current_user.dog%>
      <%= cl_image_tag @match.second_dog.photos.first.key, width: 100, height: 100, crop: :fill , class: "avatar"%>
      <h1><%= @match.second_dog.name %></h1>
    <% else %>
      <%= cl_image_tag @match.dog.photos.first.key, width: 100, height: 100, crop: :fill , class: "avatar"%>
      <h1><%= @match.dog.name %></h1>
    <% end %>
  </div>

  <div class="messages" data-match-subscription-target="messages">
    <% @match.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>
  <%= simple_form_for [@match, @message], html: { data: { action: "turbo:submit-end->match-subscription#resetForm" }, class: "d-flex align-items-center" } do |f| %>
    <button type="button" class="icon-calender" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <%= image_tag('pink-calender.svg') %>
    </button>
    <%= f.input :content, label: false, placeholder: "Dis quelque chose", wrapper_html: {class: "flex-grow-1"}, input_html: {class: "padding-input"}%>

   <button type="submit" class= "icon-plane">
      <i class="fa-regular fa-paper-plane"></i>
  </button>
  <% end %>
</div>

<div class="meeting-modal-parent" data-controller="meeting-modal" data-meeting-modal-match-id-value="<%= @match.id %>">
  <div class="modal fade" id="exampleModal" taindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <%= render "meeting_modal", match: @match, meeting: @meeting %>
    </div>
  </div>
  <div data-meeting-modal-target="hiddenMessage">
    <span>Balade planifiée !</span>
  </div>
</div>

<% content_for :meta_title, "Discussion avec #{@match.second_dog.name}" %>