config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "pages#home", as: :user_root
  end
  root to: "pages#home"

  resource :profile, only: %i[edit update index]

  resources :dogs, only: %i[index show edit update] do
    resources :likes, only: %i[create]
  end

  resources :matches, only: %i[index show] do
    resources :messages, only: %i[create]
    resources :meetings, only: %i[new create destroy]
  end

  resources :meetings, only: %i[index]

  resources :places, only: %i[index new create show] do
    resources :walks, only: %i[create destroy]
    resources :reviews, only: %i[new create index]
  end
  delete "reviews/:id", to: "reviews#destroy", as: :delete_review
  get 'all_my_review', to: 'reviews#show'
  get 'home_user', to: "pages#home_user"
  get 'home', to: 'pages#home'
  get 'faq', to: 'pages#faq'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_place, only: %i[new index create]
  def new
    # We need @place in our `simple_form_for`
    @review = Review.new
    @place = Place.find(params[:place_id])
  end

  def index
    @place = Place.find(params[:place_id])
    @reviews = Review.all
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @place = Place.find(params[:place_id])
    @review.place = @place
    @review.user = current_user

    if @review.save
      flash.alert = "Votre avis est enregistré"
      redirect_to place_reviews_path(@place)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @reviews = Review.all
  end

  def destroy
    @review = Review.find(params[:review_id])
    @review.destroy
    flash.alert = "Votre avis est supprimé"
    redirect_to all_my_review_path(@reviews)
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :photo)
  end
end

app/views/reviews/index.html.erb
<div class='review-page'>
  <h1><strong>Tous les avis du <%= @place.name %></strong></h1>

    <div class="button-add-return">
      <%= link_to "Retour", places_path, class: "button-return btn-primary"%>
      <%= link_to "Ajouter un avis", new_place_review_path(@place), class: "button-add btn-primary"%>
    </div>



  <div class="review">
        <% if @place.reviews.blank? %>
          Soyez la première personne à laisser un avis sur <%= @place.name %>.
        <% else %>

    <h2><strong>Une note moyenne de <%= @place.reviews.sum(:rating) / @place.reviews.size%> sur 5 </strong>(<%= pluralize @place.reviews.size, "avis" %>).</h2>
          <% @place.reviews.each do |review| %>
          <div class='card-review'>
            <div class="review-info">
              <p class="author"><%= cl_image_tag review.user.dog.photos.first.key, width: 50, height: 50, crop: :fill , class: "avatar"%>
              <strong class="author"><%= review.user.username %></strong>
              <%=l(review.created_at, format: "%a %e %b à %l:%M")%>
              </p>
            </div>
            <%= review.content %>
            <br>
            Je donne une note de <%= review.rating %> sur 5 à ce parc.
            </p>

          </div>
          <% end %>
        <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Ajouter un avis</h1>
<div class='review-form'>
  <%= simple_form_for [@place, @review] do |f| %>
    <%= f.input :content, label: "Votre commantaire" %>
    <%= f.input :rating, label: "Note" %>
    <%= link_to "Annuler", place_reviews_path(@place), class: "btn btn-secondary" %>
    <%= f.submit "Ajouter", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class='all-my-reviews'>
  <h1>Tous mes avis</h1>
  <%= link_to "Retour", home_user_path, class: "button-return btn-primary"%>
  <div>
    <% current_user.reviews.each do |review| %>

      <div class='card-avis'>
      <br>
      Mon commentaire :
        <p><%=review.place.name%>
        <br>
        <%= review.content %></p>
        <br>
        Je donne une note de <%= review.rating %> sur 5 à ce parc.
        <%#= link_to "Delete", delete_review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
      <br>
    <% end %>
  </div>
</div>